### ISSUE TITLE
Maximum formant frequency as a variable

### ISSUE THREAD

**Issue by agricolamz** [drammock/automated-formant-measurement-tutorial#1]
I would add a variable for the maximum formant frequency, since it can vary from speaker to speaker and influence the efficiency of Praat automatic formant detection algorithm.

https://github.com/drammock/automated-formant-measurement-tutorial/blob/6af6fe6d42f140174c35da11451ec1ad5c112c09/measure-formants-automated.praat#L92

**Comment by drammock** [comment]
If I had written the script for general usage (rather than for a specific live-coding demo with known data), I probably would have done that. Feel free to do so in your own fork, or as a pull request here.
